
title: Yusuf K. Bilgiç
logo: /images/bilgic.jpg
email: bilgic@geneseo.edu
description: >- # this means to ignore newlines until "baseurl:"
  Assistant Professor at Geneseo University

baseurl: "" # the subpath of your site, e.g. /blog
url: "bilgicyusuf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

author:
  name: Yusuf K. Bilgiç
  picture: /images/bilgic.jpg

# Build settings
#theme: minima
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US
read_time: true
mathjax:
  enable: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
markdown: kramdown
feed:
  path: atom.xml

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/yekabe
    icon: fab fa-github-square

copyright: "2020 Yusuf Bilgic"